"""empty message

Revision ID: 268fdc97cb49
Revises: 918947fd8d1d
Create Date: 2026-01-03 18:03:44.880792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268fdc97cb49'
down_revision = '918947fd8d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE mediatype AS ENUM ('IMAGE', 'VIDEO')")
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
