"""empty message

Revision ID: 918947fd8d1d
Revises: 3db386ceca66
Create Date: 2026-01-03 17:53:39.394126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918947fd8d1d'
down_revision = '3db386ceca66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('media')
    op.drop_table('comment')
    # ### end Alembic commands ###
